# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# nameブロック: ワークフローの名前を定義
name: Node.js CI

# onブロック: ワークフローを実行するイベントを定義
on:
  # pushされた時に実行
  push:
    branches: [main]
  #プルリクエストが作成された時 (prが新しいコミットで更新された時、またはprがリオープンされた時)
  pull_request:
    branches: [main]

# jobブロック: ワークフロー内で実行されるジョブを定義
jobs:
  build:
    # runs-onブロック: ワークフローが実行される仮想環境(ランナー)を定義
    runs-on: ubuntu-latest

    # strategyブロック: ワークフローを特定のパラメータの組み合わせで繰り返し実行する「マトリクス」を定義
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # stepsブロック: ジョブで実行されるステップを定義
    steps:
      # use: アクションを呼び出す
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # run: コマンドを実行
      - run: npm ci # ライブラリinstall
      - run: npm run build --if-present # ビルド
      - run: npm test # 自動テスト
